name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19da21f072e0fd5d077c9e6c7438b7da7c0357f6c3c370c222abef2e4886d794"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
