name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "783b31525845e41f0111025746bd7abd815f36edaded27bac40d03a96912ac6a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
