name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba32902585da0a3c3ee47a3db8d17f1794d8b976056c5022dbd8c7276488cad6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21"]
