name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b690fc3a9dc8b1d349a1ff09a5c4d02d0424d8242430854ea747f910e7415675"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21"]
