name = "Brassworks SMP Modpack"
author = "swzo, Pipo1660"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd2878d9501233f0de775b86ff289457796680b411755fabcd74f8f39c43fc16"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[options]
acceptable-game-versions = ["1.21"]
