name: Build CurseForge Modpack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Read pack.toml info
      - name: Read pack.toml info
        id: get_info
        run: |
          VERSION=$(grep '^version =' pack.toml | sed 's/version = "\(.*\)"/\1/')
          NAME=$(grep '^name =' pack.toml | sed 's/name = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "Successfully read Pack Name: $NAME"
          echo "Successfully read Pack Version: $VERSION"

      # 3. Make packwiz executable
      - name: Make packwiz executable
        run: chmod +x ./packwiz-linux

      # 4. Build CurseForge pack
      - name: Build CurseForge pack
        run: ./packwiz-linux curseforge export

      # 5. Upload generated zip to Actions artifacts
      - name: Upload generated modpack zip
        uses: actions/upload-artifact@v4
        with:
          name: Generated Modpack - ${{ steps.get_info.outputs.name }} v${{ steps.get_info.outputs.version }}
          path: '*.zip'
